version: '2'
services:
  oracle:
    image: menthamin/oracle-xe-11g-hmall
    container_name: oracle11g
    volumes:
      - /opt/oracle-data:/u01/app/oracle-data
      
    ports:
      - 1521:1521
      - 8080:8080